
import { Review } from './types';

export const dummyReviews: Review[] = [
  {
    id: '1',
    rating: 4,
    text: 'Отличный товар, но есть небольшие недочеты. Доставка была быстрой, качество соответствует цене.',
    date: '2023-05-15',
    articleId: 'WB-12345',
    processed: false,
    canEdit: true,
  },
  {
    id: '2',
    rating: 2,
    text: 'Не соответствует описанию. Цвет совсем другой, размер меньше указанного.',
    date: '2023-05-14',
    articleId: 'WB-67890',
    processed: false,
    canEdit: true,
  },
  {
    id: '3',
    rating: 5,
    text: 'Прекрасный товар, очень довольна покупкой! Рекомендую.',
    date: '2023-05-13',
    articleId: 'WB-54321',
    processed: false,
    canEdit: true,
  },
  {
    id: '4',
    rating: 3,
    text: 'Среднее качество. Ожидала большего за эту цену.',
    date: '2023-05-12',
    articleId: 'WB-09876',
    processed: false,
    canEdit: true,
  },
  {
    id: '5',
    rating: 1,
    text: 'Ужасное качество. Товар пришел поврежденным.',
    date: '2023-05-11',
    articleId: 'WB-13579',
    processed: false,
    canEdit: true,
  },
  {
    id: '6',
    rating: 5,
    text: 'Идеально! Всё точно как в описании.',
    date: '2023-05-10',
    articleId: 'WB-24680',
    processed: true,
    response: 'Спасибо за ваш отзыв! Мы рады, что вам понравился товар.',
    canEdit: true,
  },
  {
    id: '7',
    rating: 2,
    text: 'Разочарована покупкой. Качество ниже среднего.',
    date: '2023-05-09',
    articleId: 'WB-97531',
    processed: true,
    response: 'Приносим извинения за неудобства. Пожалуйста, свяжитесь с нами для решения вашей проблемы.',
    canEdit: false,
  },
  {
    id: '8',
    rating: 4,
    text: 'Хороший товар за свои деньги.',
    date: '2023-05-08',
    articleId: 'WB-86420',
    processed: true,
    response: 'Благодарим за ваш отзыв! Будем рады видеть вас снова.',
    canEdit: true,
  }
];
