// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmrisiqgrxyvijsvpwrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtcmlzaXFncnh5dmlqc3Zwd3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NjM3ODcsImV4cCI6MjA1OTAzOTc4N30.1oog7c19Z3yleJZYpYq-Ir2ycJFtKXSMXsQn5VVZUOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);